"""ORM models. Keep in sync with db/schema.sql (generated by scripts/gen_schema.py)."""
from __future__ import annotations

from datetime import date, datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    Index,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

JSONType = JSON().with_variant(JSONB(), "postgresql")


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


# --- opportunity statuses -------------------------------------------------
class Status:
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"
    EXPIRED = "expired"
    ALL = (PENDING, APPROVED, REJECTED, SCHEDULED, PUBLISHED, EXPIRED)


class OppType:
    ROSTER = "roster_opportunity"
    VERIFIED = "verified_need"


# --------------------------------------------------------------------------
class School(Base):
    __tablename__ = "schools"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    slug: Mapped[str] = mapped_column(String(120), unique=True)
    name: Mapped[str] = mapped_column(String(200))
    short_name: Mapped[str | None] = mapped_column(String(80))
    division: Mapped[str | None] = mapped_column(String(40))  # "NCAA D1", "NCAA D2", "NAIA", "JUCO"
    conference: Mapped[str | None] = mapped_column(String(120))
    state: Mapped[str | None] = mapped_column(String(40))
    athletics_domain: Mapped[str | None] = mapped_column(String(200))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    teams: Mapped[list["Team"]] = relationship(back_populates="school")


class Team(Base):
    __tablename__ = "teams"
    __table_args__ = (UniqueConstraint("school_id", "sport"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    school_id: Mapped[int] = mapped_column(ForeignKey("schools.id", ondelete="CASCADE"))
    sport: Mapped[str] = mapped_column(String(40), index=True)
    adapter: Mapped[str] = mapped_column(String(40))  # "sidearm", "fixture", ...
    base_url: Mapped[str] = mapped_column(String(300))
    sport_path: Mapped[str] = mapped_column(String(80))  # "baseball" in /sports/baseball/roster
    active: Mapped[bool] = mapped_column(Boolean, default=True)
    notes: Mapped[str | None] = mapped_column(Text)
    school: Mapped[School] = relationship(back_populates="teams")


class Season(Base):
    __tablename__ = "seasons"
    __table_args__ = (UniqueConstraint("sport", "label"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    sport: Mapped[str] = mapped_column(String(40))
    label: Mapped[str] = mapped_column(String(20))  # "2026" or "2025-26"
    start_year: Mapped[int] = mapped_column(Integer)


class Source(Base):
    __tablename__ = "sources"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    team_id: Mapped[int | None] = mapped_column(ForeignKey("teams.id", ondelete="SET NULL"), index=True)
    url: Mapped[str] = mapped_column(Text)
    kind: Mapped[str] = mapped_column(String(40))  # roster | stats | official_statement | other
    tier: Mapped[str] = mapped_column(String(1))  # A | B | C
    title: Mapped[str | None] = mapped_column(Text)
    publisher: Mapped[str | None] = mapped_column(String(200))
    author_account: Mapped[str | None] = mapped_column(String(200))  # required for social media
    season_label: Mapped[str | None] = mapped_column(String(20))
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    http_status: Mapped[int | None] = mapped_column(Integer)
    available: Mapped[bool] = mapped_column(Boolean, default=True)
    content_hash: Mapped[str | None] = mapped_column(String(64))
    error: Mapped[str | None] = mapped_column(Text)


class RosterSnapshot(Base):
    __tablename__ = "roster_snapshots"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    team_id: Mapped[int] = mapped_column(ForeignKey("teams.id", ondelete="CASCADE"), index=True)
    season_id: Mapped[int] = mapped_column(ForeignKey("seasons.id"))
    source_id: Mapped[int] = mapped_column(ForeignKey("sources.id"))
    collected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    player_count: Mapped[int] = mapped_column(Integer, default=0)
    entries: Mapped[list["RosterEntry"]] = relationship(back_populates="snapshot", cascade="all, delete-orphan")


class Player(Base):
    __tablename__ = "players"
    __table_args__ = (UniqueConstraint("team_id", "site_player_id"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    team_id: Mapped[int] = mapped_column(ForeignKey("teams.id", ondelete="CASCADE"), index=True)
    site_player_id: Mapped[str | None] = mapped_column(String(40))
    full_name: Mapped[str] = mapped_column(Text)
    name_key: Mapped[str] = mapped_column(String(160), index=True)


class RosterEntry(Base):
    __tablename__ = "roster_entries"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    snapshot_id: Mapped[int] = mapped_column(ForeignKey("roster_snapshots.id", ondelete="CASCADE"), index=True)
    player_id: Mapped[int] = mapped_column(ForeignKey("players.id", ondelete="CASCADE"))
    jersey: Mapped[str | None] = mapped_column(String(16))
    position_raw: Mapped[str | None] = mapped_column(Text)
    position_group: Mapped[str | None] = mapped_column(String(20))
    secondary_group: Mapped[str | None] = mapped_column(String(20))
    position_confidence: Mapped[float | None] = mapped_column(Float)
    is_two_way: Mapped[bool] = mapped_column(Boolean, default=False)
    class_year_raw: Mapped[str | None] = mapped_column(Text)
    class_year: Mapped[str | None] = mapped_column(String(10))  # FR SO JR SR GR UNKNOWN
    redshirt: Mapped[bool | None] = mapped_column(Boolean)
    eligibility_remaining: Mapped[int | None] = mapped_column(Integer)  # NULL unless reliably published
    height: Mapped[str | None] = mapped_column(Text)
    weight: Mapped[str | None] = mapped_column(Text)
    bats: Mapped[str | None] = mapped_column(String(2))
    throws: Mapped[str | None] = mapped_column(String(2))
    hometown: Mapped[str | None] = mapped_column(Text)
    high_school: Mapped[str | None] = mapped_column(Text)
    previous_school: Mapped[str | None] = mapped_column(Text)
    snapshot: Mapped[RosterSnapshot] = relationship(back_populates="entries")
    player: Mapped[Player] = relationship()


class PlayerStat(Base):
    __tablename__ = "player_stats"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    team_id: Mapped[int] = mapped_column(ForeignKey("teams.id", ondelete="CASCADE"), index=True)
    season_id: Mapped[int] = mapped_column(ForeignKey("seasons.id"))
    source_id: Mapped[int] = mapped_column(ForeignKey("sources.id"))
    player_id: Mapped[int | None] = mapped_column(ForeignKey("players.id", ondelete="SET NULL"))
    stat_type: Mapped[str] = mapped_column(String(30))  # batting | pitching | fielding ...
    name_raw: Mapped[str] = mapped_column(Text)
    jersey: Mapped[str | None] = mapped_column(String(16))
    site_player_id: Mapped[str | None] = mapped_column(String(40))
    stats: Mapped[dict] = mapped_column(JSONType, default=dict)
    raw: Mapped[dict] = mapped_column(JSONType, default=dict)
    collected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)


class Opportunity(Base):
    __tablename__ = "opportunities"
    __table_args__ = (Index("ix_opp_sport_status", "sport", "status"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    fingerprint: Mapped[str] = mapped_column(String(64), unique=True)
    sport: Mapped[str] = mapped_column(String(40))
    school_id: Mapped[int] = mapped_column(ForeignKey("schools.id"))
    team_id: Mapped[int] = mapped_column(ForeignKey("teams.id"))
    opportunity_type: Mapped[str] = mapped_column(String(30), default=OppType.ROSTER)
    position_group: Mapped[str] = mapped_column(String(20))
    position_label: Mapped[str] = mapped_column(Text)
    target_season: Mapped[str] = mapped_column(String(20))
    stats_season: Mapped[str | None] = mapped_column(String(20))
    roster_season: Mapped[str | None] = mapped_column(String(20))
    departure_basis: Mapped[str | None] = mapped_column(String(30))  # observed | class_year_projection | verified
    signal: Mapped[float] = mapped_column(Float, default=0)
    confidence: Mapped[str] = mapped_column(String(10), default="LOW")
    data_quality: Mapped[float | None] = mapped_column(Float)
    components: Mapped[dict] = mapped_column(JSONType, default=dict)
    metrics: Mapped[dict] = mapped_column(JSONType, default=dict)
    reason: Mapped[str | None] = mapped_column(Text)
    evidence_hash: Mapped[str | None] = mapped_column(String(64))
    status: Mapped[str] = mapped_column(String(20), default=Status.PENDING)
    status_note: Mapped[str | None] = mapped_column(Text)
    telegram_text: Mapped[str | None] = mapped_column(Text)
    telegram_text_edited: Mapped[bool] = mapped_column(Boolean, default=False)
    x_teaser: Mapped[str | None] = mapped_column(Text)
    low_confidence_override: Mapped[bool] = mapped_column(Boolean, default=False)
    first_detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    last_analyzed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    last_verified_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    source_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    scheduled_for: Mapped[date | None] = mapped_column(Date)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)

    school: Mapped[School] = relationship()
    team: Mapped[Team] = relationship()
    evidence: Mapped[list["OpportunityEvidence"]] = relationship(
        back_populates="opportunity", cascade="all, delete-orphan", order_by="OpportunityEvidence.id"
    )
    sources: Mapped[list[Source]] = relationship(secondary="opportunity_sources")


class OpportunityEvidence(Base):
    __tablename__ = "opportunity_evidence"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    opportunity_id: Mapped[int] = mapped_column(ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    kind: Mapped[str] = mapped_column(String(30))  # summary | player | statement
    label: Mapped[str] = mapped_column(Text)
    data: Mapped[dict] = mapped_column(JSONType, default=dict)
    source_id: Mapped[int | None] = mapped_column(ForeignKey("sources.id", ondelete="SET NULL"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    opportunity: Mapped[Opportunity] = relationship(back_populates="evidence")
    source: Mapped[Source | None] = relationship()


class OpportunitySource(Base):
    __tablename__ = "opportunity_sources"
    opportunity_id: Mapped[int] = mapped_column(ForeignKey("opportunities.id", ondelete="CASCADE"), primary_key=True)
    source_id: Mapped[int] = mapped_column(ForeignKey("sources.id", ondelete="CASCADE"), primary_key=True)


class ScoreHistory(Base):
    __tablename__ = "score_history"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    opportunity_id: Mapped[int] = mapped_column(ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    old_signal: Mapped[float | None] = mapped_column(Float)
    new_signal: Mapped[float] = mapped_column(Float)
    old_confidence: Mapped[str | None] = mapped_column(String(10))
    new_confidence: Mapped[str] = mapped_column(String(10))
    reason: Mapped[str | None] = mapped_column(Text)


class TelegramChannel(Base):
    __tablename__ = "telegram_channels"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    sport: Mapped[str] = mapped_column(String(40), unique=True)
    title: Mapped[str] = mapped_column(String(120))
    channel_env_var: Mapped[str] = mapped_column(String(80))  # the ID itself stays in env
    active: Mapped[bool] = mapped_column(Boolean, default=True)


class PublishingQueue(Base):
    __tablename__ = "publishing_queue"
    __table_args__ = (UniqueConstraint("sport", "publish_date"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    sport: Mapped[str] = mapped_column(String(40))
    publish_date: Mapped[date] = mapped_column(Date)
    opportunity_id: Mapped[int] = mapped_column(ForeignKey("opportunities.id", ondelete="CASCADE"))
    status: Mapped[str] = mapped_column(String(20), default="scheduled")  # scheduled|publishing|published|failed|blocked
    note: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    opportunity: Mapped[Opportunity] = relationship()


class PublishedPost(Base):
    __tablename__ = "published_posts"
    __table_args__ = (UniqueConstraint("opportunity_id", "channel_ref", "mode"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    opportunity_id: Mapped[int] = mapped_column(ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    sport: Mapped[str] = mapped_column(String(40))
    channel_ref: Mapped[str] = mapped_column(String(80))  # env var name, not the id
    mode: Mapped[str] = mapped_column(String(10))  # live | test | dry_run
    telegram_message_id: Mapped[int | None] = mapped_column(Integer)
    text: Mapped[str] = mapped_column(Text)
    x_teaser: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(20))  # sent | logged | failed
    error: Mapped[str | None] = mapped_column(Text)
    sent_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)


class EventLog(Base):
    __tablename__ = "event_log"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, index=True)
    level: Mapped[str] = mapped_column(String(10))
    event: Mapped[str] = mapped_column(String(60), index=True)
    sport: Mapped[str | None] = mapped_column(String(40))
    entity_type: Mapped[str | None] = mapped_column(String(40))
    entity_id: Mapped[int | None] = mapped_column(Integer)
    message: Mapped[str] = mapped_column(Text)
    data: Mapped[dict] = mapped_column(JSONType, default=dict)
